DB_USERNAME='aa_nadim'
DB_PASSWORD='aa_nadim123'
DB_NAME='scraping_db'
DB_PORT='5432'
DB_HOST='postgresDB_Container'
OLLAMA_HOST='http://ollama:11434'
SECRET_KEY='django-insecure-nc4($e*vaa^7ftbpg^5y8yz-5a(-n18-*#ln^wpbtw5a0-@e5('